제어 전환 명령문
=========

- continue
    
    continue문 아래의 코드들은 작동시키지 않고 다음 반복문의 반복을 시작하게 해주는 역할을 한다. 
    
    ```swift
    import Foundation
    
    let numbers: [Int] = [1, 4]
    let numbers2: [Int] = [100, 200, 300]
    
    for i in numbers {
        continue
        print(i)
    }
    
    for j in numbers2 {
        print(j) // 100, 200, 300
    }
    ```
    
    i는 프린트되지 않고 j만 프린트되어서 나온다.    
    


- break
    
    루프 문을 종료시킨다.
    
    ```swift
    let numbers: [Int] = [1, 4]
    for i in numbers {
        print(i) // 1
        break
    }
    ```
    
    첫 객체만 프린트되고 다음에 바로 루프문을 종료시키는 break 나왔으므로 오직 1만이 출력되서 나온다.
    
- throw
    
    함수, 이니셜라이저, 메서드는 throw 키워드를 사용하면 오류를 던질 수 있다.
    
    throws 키워드를 사용한 함수는 동작 도중 오류가 발생하면 호출한 코드에 오류를 알릴 수 있다.
    
- fallthrough
    
    switch문 안에서만 사용할 수 있다. 
    
    예약 기능을 가지고 있다. 보통 switch문에서는 하나의 case를 거치면 다른 case문은 무시하고 해당 
    
    switch문을 빠져나가는게 일반적이다. 
    
    하지만 fallthrough를 사용하면, 하나의 case문이 거친 뒤, 그 다음 case문의 내용을 이어서 실행하는 
    
    동작이 가능하다. 마지막 case문에는 fallthrough를 넣는 것이 불가능하다. 왜냐면, 다음 case문이 존재하지 않기 때문이다. 
    
    ```swift
    import Foundation
    
    enum Name {
        case 맹구
        case 철수
        case 짱구
        case 유리
        case 훈발놈
    }
    
    var myFriend: Name = .맹구
    
    switch myFriend {
    case .맹구:
        print("맨체스터 유나이티드")
        fallthrough 
    case .철수:
        print("철수")
    case .유리:
        print("유리")
    case .짱구:
        print("짱구")
    case .훈발놈:
        print("훈발놈")
    }
    ```
    
    fallthrough문 때문에 맨체스터 유나이티드뿐만 아니라 철수까지 프린트 된다. 철수 case문에도 fallthrough를 넣었다면 “유리”도 출력되었을 것이다.
    
    ```swift
    switch myFriend {
    case .맹구:
        print("맨체스터 유나이티드")
        fallthrough
    case .철수:
        fallthrough
        print("철수")
    case .유리:
        print("유리")
    case .짱구:
        print("짱구")
    case .훈발놈:
        print("훈발놈")
    }
    ```
    
    철수를 프린트하기 전에 fallthrough를 넣었다면 맨체스터 유나이티드와 유리만 프린트 된다.
    
    fallthrough를 통해 철수를 프린트 하기전에 다음 case문으로 넘어갔기 때문이다.
